# 30. 이너 & 예외처리

### 01. 이너클래스 

- inner class

  - 정적 이너 클래스
  - 지역 이너 클래스

- 아우터(outer)클래스의 모든 접근지정자의 멤버 접근 가능

  ```java
  class OuterClass {
    class InnerClass {...}
  }
  ```





### 02. 이너 인터페이스

- inner interface
  - 정적(static)이너인터페이스만 가능(static생략시 자동 추가)
- 특징
  1. 아우터 클래스와 밀접한 관계가 있는 경우에 정의
  2. UI 이벤트 처리에 가장 많이 사용(클릭, 터치 등)
  3. static을 생략한 경우 컴파일러는 자동으로 static 삽입

```java
class A{
  // ...
  static interface B{ // static 생략해도 자동으로 추가
    void bcd();
  }
}
```



### 03. 예외(Exception)

> **Run time error**
>
> - 실행 시 발생하는 에러
> - 프로그램이 종료 됨 (중지)
> - 예전 C언어에서는 Run time error를 개발자가 모두 예측해서 처리해야 함.
>   - 경험이 많지 않거나, 새로운 분야를 코딩할때 문제가 생김

- **예외(Exception)**
  - java에서는 run time error를 exception 라고 함
  - 예외 처리
    - Exception이 발생했을 때 프로그램이 종료되지 않도록 하는 것이 주 목적
    - 신뢰성 있는 앱 개발 가능 (웬만해서는 막을 수 없음)
- **고가용성 (High Availablity)**
  - 항상 사용할 수 있는 상태. 서버는 고가용성이 중요



> **Java의 주요특징 3가지**
>
> 1. JVM
> 2. 예외처리
> 3. Garbage Collector



- **java의 단점**
  - null이 들어가면 호출 할 수 없음
  - null point exception이 필요

```java
if(a!=null){
  a.show();
}
```

- `null safety` (null로부터 안전한 코딩)



#### 3-1. 예외 처리

- 일반 예외(Check Exception)
  - 컴파일 자체가 불가능
- 실행 예외
  - 예외발생시 프로그램 종료 (예외메세지 출력)

\* 예외처리를 통해 정상실행 가능

#### 3-2. `try` `catch` `finally`

```java
try{
  // 예외 발생 가능 코드
  // 일반예외/실행예외 발생 가능 코드
}
catch(예외클래스명 참조변수명){
  // 해당 예외가 발생한 경우 처리 블록
}
finally{
  // 예외 발생여부에 상관없이 무조건 실행블록
  // close code 입력(메모리 회수, 자원관리 원활)
}
```



- 오류 코드를 예외처리 해봅시다.

  ```java
  public class TryCatchFinally {
  	public static void main(String[] args) {
  		System.out.println(3/0); // 산수 오류(ArithmeticException)
  		System.out.println("이부분이 실행될까요?"); // 오류 때문에 프로그램 중지 및 실행X
  	}
  }
  ```

  - 예외처리 후

    ```java
    public class TryCatchFinally {
    	public static void main(String[] args) {
    		try {
    			System.out.println(3/0);
    		}catch(Exception e){}
          	// 오류가 발생했어도 실행 됨
    		System.out.println("이부분이 실행될까요?");
    	}
    }
    ```

    - Exception(예외)의 최상위 클래스는 **Exception**

    - 예외가 발생해도 어떤 종류인지 알 수 없을 때는 최상위인 `Exceptio`으로 catch의 인자를 받아 예외처리

    - **최종 코드**

      ```java
      import java.util.Scanner;

      public class TryCatchFinally {

      	public static void main(String[] args) {
      		Scanner s=new Scanner(System.in);
      		try {
      			System.out.println("분자 : ");
      			int num1=s.nextInt();
      			System.out.println("분모 : ");
      			int num2=s.nextInt();
      			System.out.println(num1/num2);		
      		}catch(ArithmeticException e){ // 분모가 0일 경우 무한값이 나오기 때문에 오류
      			e.printStackTrace(); // debugging용 에러 확인
      			System.out.println(e.getMessage()); // 오류 메세지
                  // End User용
      			System.out.println("분모에는 0이 들어갈 수 없습니다.");
      		}finally {
      			// 무조건 실행, 확실한 방법
      			s.close();
      		}
      	}
      }
      ```

      - End User(사용자)의 입장에 이해하기 쉽도록 예외처리 작성



#### 3-3. `try with resource`

- 리소스 자동해제 예외 처리
  - JDK 1.7 이후 리소스를 자동으로 해지할 수 있는 문법구조
  - 리소스 자동해제 객체는 반드시 close 메서드를 포함해야 함
    - 리소스 자동해제 객체는 AutoCloseable 인터페이스를 구현해야 함



#### 3-4. `throws`

- 예외(Exception)의 전가(thows)

  - 다중 전가 (여러개의 예외 전가 가능)

  ```java
  void abc(){
    try{
      bcd();
    }
    // 각 예외마다 처리가 다를 때 사용
    // 섬세하게 예외처리 할 수 있음
    catch(ClassNotFoundException e){}
    catch(InterruptedException e){}
  }
  ```



- *예제)*

  ```java
  import java.util.Scanner;

  class A {
      int num1;
      int num2;

      // throws는 직접 예외를 처리하지 않고 메서드를 호출한 쪽에서
      // 예외를 처리하도록 예외를 전달(throws)
      int divide() throws ArithmeticException {
          return this.num1 / this.num2;
      }
  }

  public class ThrowTest {
      public static void main(String[] args) {
          A a = new A();
          Scanner s = new Scanner(System.in);
          
          System.out.print("분자 : ");
          a.num1 = s.nextInt();
          System.out.print("분모 : ");
          a.num2 = s.nextInt();
          
          try {
              System.out.println("결과: " + a.divide());
          } catch (ArithmeticException e) {
          	e.printStackTrace();
              System.out.println("오류: 0으로 나눌 수 없습니다."); // 예외 처리
          }

          s.close(); // Scanner 닫기
      }
  }
  ```

  ​



#### 3-5. 예외 클래스 사용자 정의

```java
// 사용자정의 Exception
class MinusException extends Exception{
	//생성자 오버로딩
	public MinusException() {
		super(); // 부모클래스의 생성자 호출
	}
	public MinusException(String message) {
		super(message); // 부모클래스의 생성자 호출
	}
}
class OverException extends Exception{
	//생성자 오버로딩
	public OverException() {
		super(); // 부모클래스의 생성자 호출
	}
	public OverException(String message) {
		super(message); // 부모클래스의 생성자 호출
	}
}

class GrageCalc{
	void checkScore(int score) throws MinusException,OverException{
		if(score<0) {
			throw new MinusException("예외 발생 : 음수값 입력");
		}else if(score>100) {
			throw new OverException("예외 발생 : 100점 초과");
		}
	}
}

public class UserExceptionExample {
	public static void main(String[] args) {
		GrageCalc a=new GrageCalc();
		try {
			a.checkScore(0);
			a.checkScore(150);
		}catch(MinusException | OverException e) {
			System.out.println(e.getMessage());
		}
	}
}
```



> **상황 발생**
>
> - 실무에서 여러개발자가 협업 할 때 같은 내용도 서로 다른 표현을 사용
>   - 통합했을 때 메세지 통일성이 없어짐
>   - *예)*
>     - 삭제하시겠습니까?
>     - 정말 삭제합니까?
>     - 진짜 삭제할건가요?
> - 사용자정의 Exception을 만들어서 같이 공유하면 같은 메세지를 사용할 수 있음
>   - 통합했을 때 통일성이 유지됨

